site_name: Cedar
nav:
    - CEDAR Form Overview:
      - I found my CEDAR form. Now What?: index.md
    - CEDAR Form Sections:
      - Minimal Info: minimal-info.md
      - (Meta)data Location: meta-data-location.md
      - Data Availability: data-availability.md
      - Study Translational Focus: study-translational-focus.md
      - Study Type: study-type.md
      - Human Treatment Applicability: human-treatment-applicability.md
      - Human Condition Applicability: human-condition-applicability.md
      - Human Subject Applicability: human-subject-applicability.md
      - Data: data.md
    - CEDAR Hints: 
      - Expand or Collapse CEDAR Form Section: expand-or-collapse-cedar-form-section.md
      - CEDAR Field Help Text: cedar-field-help-text.md
      - Identify and Complete CEDAR Array Type Field: complete-cedar-array-field.md 
      - Identify and Complete CEDAR Date Type Field: complete-cedar-date-field.md 
      - Saving CEDAR Form: save-cedar-form.md
      - Update CEDAR Form Metadata: update-cedar-form-metadata.md
      - Sharing your CEDAR form with other members of your study team: sharing-your-cedar-form.md
theme: readthedocs
markdown_extensions:
    - admonition
    - pymdownx.details
