site_name: I Found My CEDAR Form. Now What?
nav:
    - CEDAR Form Overview:
      - I found my CEDAR form. Now What?: index.md
    - CEDAR Form Sections:
      - Minimal Info: minimal-info.md
    - CEDAR Hints: 
      - Expand or Collapse CEDAR Form Section: expand-or-collapse-cedar-form-section.md
      - CEDAR Field Help Text: cedar-field-help-text.md
      - Save CEDAR Form: save-cedar-form.md
theme: readthedocs
markdown_extensions:
    - admonition
